#!/usr/bin/env bash

# setup $HOME/.dotfiles

# preconditions
#   dotfiles

DOTFILES_CONFIG_DIR="${HOME}/dotfiles/home"
CONFIG_MAP=(
  "bash.bashrc:.bashrc"
  "zsh.zshrc:.zshrc"
  "vimrc:.vimrc"
  "sshconfig:.ssh/config"
  "tmux.conf:.tmux.conf"
  "gitconfig:.gitconfig"
)

# echo [INFO] [WARNING] [ERROR]
# Black         0;30    Dark Gray       1;30
# Red           0;31    Light Red       1;31
# Green         0;32    Light Green     1;32
# Orange        0;33    Yellow          1;33
# Blue          0;34    Light Blue      1;34
# Purple        0;35    Light Purple    1;35
# Cyan          0;36    Light Cyan      1;36
# Light Gray    0;37    White           1;37

echoinfo() {
  #echo -e "\e[32m[INFO]\e[0m"
  unset ARG
  for ARG in "$@"
  do
    echo -e "\e[32m$ARG\e[0m"
  done
  unset ARG
}

echowarning() {
  #echo -e "\e[33m[WARNING]\e[0m"
  unset ARG
  for ARG in "$@"
  do
    echo -e "\e[33m$ARG\e[0m"
  done
  unset ARG
}

echoerror() {
  #echo -e >&2 "\e[31m[ERROR]\e[0m"
  unset ARG
  for ARG in "$@"
  do
    echo -e >&2 "\e[31m$ARG\e[0m"
  done
  unset ARG
}

backup_file() {
  local file=$1
  if [[ -e $file ]]; then
    local timestamp=$(date +%Y%m%d%H%M%S)
    mv -v "$file" "${file}.${timestamp}.bak"
  fi
}

deploy_config() {
  local action=$1  # deploy/clean
  local source=$2
  local target=$3
  local backup="${target}.*.bak"

  case $action in
    deploy)
      backup_file "$target"
      cp -v "$source" "$target" || echoerror "failed to copy $source to $target"
      chmod 600 "$target" || echoerror "failed to set permissions on $target"

      local latest_backup=$(ls -1t $backup 2>/dev/null | head -1)
      if [[ -n "$latest_backup" ]]; then
        echoinfo "latest_backup: $(basename $latest_backup)"
        if awk '/\[custom\]/ {i=1;next};i' "$latest_backup" >> "$target"; then
          awk '/\[custom\]/ {i=1;next};i' "$latest_backup"
        else
          echowarning "failed to awk latest_backup [custom] to $target"
        fi
      else
        echowarning "no latest_backup for $target"
      fi
      echo
      ;;
    clean)
      rm -vf $backup || echoerror "failed to clean $backup"
      ;;
  esac
}

main() {
  local action=${1:-deploy}

  for config in "${CONFIG_MAP[@]}"; do
    deploy_config "$action" "$DOTFILES_CONFIG_DIR/${config%:*}" "$HOME/${config#*:}"
  done

  #echoinfo "fc-cache -f"
  #fc-cache -f
  #echoinfo "Monospace"
  #fc-match -s monospace | head -n 2
  #echoinfo "Sans-Serif"
  #fc-match -s sans-serif | head -n 2
  #echoinfo "Serif"
  #fc-match -s serif | head -n 2
}

main "$@"
